
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lexer_tests.out is a Catch v2.13.4 host application.
Run with -? for options

-------------------------------------------------------------------------------
recognizes_decimal_integers
-------------------------------------------------------------------------------
/home/aleng/CodingProjects/CompilerPractice/lexer/lexer_test.cpp:61
...............................................................................

/home/aleng/CodingProjects/CompilerPractice/lexer/lexer_test.cpp:64: FAILED:
  REQUIRE( l.next_token().type == token::TokenType::Int )
due to unexpected exception with :

-------------------------------------------------------------------------------
recognizes_hex_integers
-------------------------------------------------------------------------------
/home/aleng/CodingProjects/CompilerPractice/lexer/lexer_test.cpp:68
...............................................................................

/home/aleng/CodingProjects/CompilerPractice/lexer/lexer_test.cpp:71: FAILED:
  REQUIRE( l.next_token().type == token::TokenType::Int )
due to unexpected exception with :

-------------------------------------------------------------------------------
recognizes_doubles
-------------------------------------------------------------------------------
/home/aleng/CodingProjects/CompilerPractice/lexer/lexer_test.cpp:76
...............................................................................

/home/aleng/CodingProjects/CompilerPractice/lexer/lexer_test.cpp:79: FAILED:
  REQUIRE( l.next_token().type == token::TokenType::Double )
due to unexpected exception with :

-------------------------------------------------------------------------------
recognizes_doubles_in_scientific_notation
-------------------------------------------------------------------------------
/home/aleng/CodingProjects/CompilerPractice/lexer/lexer_test.cpp:85
...............................................................................

/home/aleng/CodingProjects/CompilerPractice/lexer/lexer_test.cpp:88: FAILED:
  REQUIRE( l.next_token().type == token::TokenType::Double )
due to unexpected exception with :

-------------------------------------------------------------------------------
recognizes_arithmetic_operators
-------------------------------------------------------------------------------
/home/aleng/CodingProjects/CompilerPractice/lexer/lexer_test.cpp:124
...............................................................................

/home/aleng/CodingProjects/CompilerPractice/lexer/lexer_test.cpp:134: FAILED:
  REQUIRE( l.next_token().type == token::TokenType::Int )
due to unexpected exception with :

-------------------------------------------------------------------------------
recognizes_comparison_operators
-------------------------------------------------------------------------------
/home/aleng/CodingProjects/CompilerPractice/lexer/lexer_test.cpp:157
...............................................................................

/home/aleng/CodingProjects/CompilerPractice/lexer/lexer_test.cpp:157: FAILED:
due to unexpected exception with :

===============================================================================
test cases: 20 | 14 passed | 6 failed
assertions: 69 | 63 passed | 6 failed

